version: "3.0"
services:
  frontend:
    build: .
    container_name: frontend_app
    restart: on-failure
    ports:
      - '${FRONTEND_PORT}:80'
    environment:
      BACKEND_PORT: ${BACKEND_PORT}