# fly.toml app configuration file generated for my-rotulo-late-meadow-4005 on 2023-12-09T01:23:13-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "my-rotulo-late-meadow-4005"
primary_region = "gru"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
